In [13]:
from Data_Handler.DataReader import DataReader
import numpy as np
import pandas as pd

dataReader= DataReader()
URM = dataReader.load_augmented_binary_urm()
URM_aug,ICM = dataReader.pad_with_zeros_ICMandURM(URM)



urm=dataReader.csr_to_dataframe(URM_aug)
icm=dataReader.load_icm_df()

user_ids=urm['UserID'].values
user_ids = np.unique(user_ids)
print(user_ids)

item_ids=urm['ItemID'].values
item_ids = np.unique(item_ids)
print(item_ids)

feature_ids = icm['feature_id'].values
feature_ids = np.unique(feature_ids)
print(feature_ids)


4877
[    0     1     2 ... 41626 41627 41628]
[    0     1     2 ... 27965 27966 27967]
[1 2 3 4 7]


In [1]:
# create an empty dataframe for storing UCM
ucm = pd.DataFrame(columns=['UserID','FeatureID','Data'])

# for each user we iterate over the URM
for user_id in user_ids:
    # Get the dataframe rows of the URM of a certain user
    df = urm.loc[urm['UserID'] == user_id]
    #print(df)
    # Get the unique ids of items
    item_ids_for_this_user = np.unique(df['ItemID'].values)
    #print(item_ids_for_this_user)

    # For each item the user has interacted with
    for item_id in item_ids_for_this_user:
        # Get the dataframe rows of ICM of a certain user
        df = icm.loc[icm['item_id'] == item_id]
        #print(df)
        # Get the unique ids of features
        feature_ids_for_items_of_this_user = np.unique(df['item_id'].values)
        #print(feature_ids_for_items_of_this_user)
        # Create the dataframe to append to UCM
        for feature_id in feature_ids_for_items_of_this_user:
            row_to_append = pd.DataFrame({'UserID': [user_id],'FeatureID': [feature_id], 'Data': [1]})
            #print(row_to_append)
            # Append at the end ot the dataframe UCM
            ucm = ucm.append(row_to_append)
            #print(ucm)



NameError: name 'pd' is not defined